version: '3.9'
services:
  db:
    image: mysql
    container_name: money-transfer-api-db
    ports:
      - "3306:3306"
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: testuser123
       MYSQL_USER: testuser
       MYSQL_PASSWORD: testuser123
       MYSQL_DATABASE: money_transfer_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}